### ISSUE TITLE
LUNA16-dataset(lung nodes dataset)

### ISSUE THREAD

**Issue by aszhanghuali** [rezacsedu/MultimodalDBNBreastCancer#1]
Hi @rezacsedu 
I'm so surprised to look at  the fantastic work. This is very useful to me. Could you please give me suggestions in order to run the repo successfully! 
First of all,I use LUNA16 dataset ,rather than  Gene Expression dataset.And,the data is .mhd and the label is .scv.
Secondly,how to process the dataset  then the DBN-Classification will be able to feed that data?

Looking forward to your reply！Thank you so much!

Thanks.

**Comment by rezacsedu** [comment]
Hi,

Thanks. There is a readme file containing instructions on how to use this repo. You should refer to that. Or if you have any specific question, please file an issue. 

AFAIK, the LUNA16 is an image dataset. However, we have used numeric data. And importantly, DBN is not good for such tasks. Rather I'd suggest you use CNN or Convolutional-autoencoder based techniques.

**Comment by aszhanghuali** [comment]
Hi!
Thank you for your reply!Could you give me some tutorials about Convolutional-autoencoder to process LUNA16 dataset?
Looking forward to your reply!
Thank you so much!




------------------ 原始邮件 ------------------
发件人: "Md. Rezaul Karim"<notifications@github.com>;
发送时间: 2019年4月11日(星期四) 晚上9:02
收件人: "rezacsedu/Multimodal-Deep-Belief-Net-Breast-Cancer"<Multimodal-Deep-Belief-Net-Breast-Cancer@noreply.github.com>;
抄送: "华丽丽"<1319466165@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [rezacsedu/Multimodal-Deep-Belief-Net-Breast-Cancer]LUNA16-dataset(lung nodes dataset) (#1)




Hi,
 
Thanks. There is a readme file containing instructions on how to use this repo. You should refer to that. Or if you have any specific question, please file an issue.
 
AFAIK, the LUNA16 is an image dataset. However, we have used numeric data. And importantly, DBN is not good for such tasks. Rather I'd suggest you use CNN or Convolutional-autoencoder based techniques.

**Comment by aszhanghuali** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi!I‘m sorry to bother you again!I wanna your hlep!Could I transform about the LUNA16 image dataset to  numeric data,so that I can use your repo. Hope your help!Looking forward to your reply!Thank you so much!
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1319466165
                            
                    
                        
                            
                                    1319466165@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/11/2019 21:09，华丽丽<1319466165@qq.com> wrote： 


Hi!Thank you for your reply!Could you give me some tutorials about Convolutional-autoencoder to process LUNA16 dataset?Looking forward to your reply!Thank you so much!------------------ 原始邮件 ------------------发件人: "Md. Rezaul Karim"<notifications@github.com>;发送时间: 2019年4月11日(星期四) 晚上9:02收件人: "rezacsedu/Multimodal-Deep-Belief-Net-Breast-Cancer"<Multimodal-Deep-Belief-Net-Breast-Cancer@noreply.github.com>;抄送: "华丽丽"<1319466165@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [rezacsedu/Multimodal-Deep-Belief-Net-Breast-Cancer]LUNA16-dataset(lung nodes dataset) (#1)Hi,
Thanks. There is a readme file containing instructions on how to use this repo. You should refer to that. Or if you have any specific question, please file an issue.
AFAIK, the LUNA16 is an image dataset. However, we have used. And importantly, DBN is not good for such tasks. Rather I'd suggest you use CNN or Convolutional-autoencoder based techniques.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
